root check for airmon-ng

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -2,6 +2,21 @@
 set -e
 set -u
 
+# airmon-ng doesn't work without root
+if [ -x "$(command -v id 2> /dev/null)" ]; then
+	USERID="$(id -u 2> /dev/null)"
+fi
+
+if [ -z "${USERID}" ] && [ -n "$(id -ru)" ]; then
+	USERID="$(id -ru)"
+fi
+
+if [ -n "${USERID}" ] && [ "${USERID}" != "0" ]; then
+	printf 'Run it as root\n' ; exit 1;
+elif [ -z "${USERID}" ]; then
+	printf 'Unable to determine user id, permission errors may occur.\n'
+fi
+
 VERS="v1.0"
 
 blue_hydra="false"
