usb support isn't always there

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -2,7 +2,7 @@
 set -e
 set -u
 
-VERS='v1.9.5'
+VERS='v1.9.6'
 
 blue_hydra="false"
 gentle="false"
@@ -35,6 +35,27 @@ if ! command -v pgrep > /dev/null 2>&1; then
   printf 'this tool is typically available in the "procps" package\n' >&2
   exit 1
 fi
+if [ -d /sys/bus/usb ]; then
+  if ! command -v lsusb 2>&1; then
+    printf "Please install lsusb from your distro's package manager.\n"
+    exit 1
+  else
+    LSUSB=1
+  fi
+else
+  LSUSB=0
+fi
+
+usb_check() {
+  if [ "${LSUSB}" = "0" ]; then
+    printf "This system does not appear to support usb devices but you asked for detection of a usb device.\n" >&2
+    printf "Unable to comply, /sys/bus/usb or lsusb are missing\n" >&2
+    return 1
+  else
+    return 0
+  fi
+}
+
 # On busybox/ash this returns "lsmod" because it's a built-in
 # so for this check we rely on command -v exit code and don't test -x
 if ! command -v lsmod > /dev/null 2>&1; then
@@ -195,6 +216,7 @@ printf '## kismet-autoconfig %s writing to %s\n' "${VERS}" "${kismet_site}" >&2
 printf '## WARNING: This file is generated by kismet-autoconfig and cannot be edited!!!\n' > "${kismet_site}"
 
 detect_nxp() {
+  usb_check || return 0
   nxp_usb="$(lsusb -d '15a2:0300' | wc -l)"
   if [ "${nxp_usb}" = "0" ]; then
     return 0
@@ -223,6 +245,7 @@ detect_nxp() {
 }
 
 detect_nordic() {
+  usb_check || return 0
   all_nrf_accounted="0"
   mousejack_first="1"
   nrf154a_usb="0"
@@ -335,6 +358,7 @@ detect_linuxbluetooth() {
 }
 
 detect_ubertooth() {
+  usb_check || return 0
   if [ -z "$(lsusb -d '1d50:6002' 2>&1)" ]; then
     # No ubertooth found, bail out quick
     return 0
@@ -423,37 +447,39 @@ detect_ubertooth() {
 }
 
 detect_ti() {
+  usb_check || return 0
   ti16ae_first="1"
   ti16b3_first="1"
   IFS='
 '
-for device in $(lsusb -d '0451:' | tr ":" " "| awk '{print $6":"$7,$2"-"$4}' | sort); do
-  PID="$(printf '%s' "${device}" | awk '{print $1}' | awk -F: '{print $2}')"
-  BUS="$(printf '%s' "${device}" | awk '{print $2}')"
-  case "${PID}" in
-    16ae)
-      #Texas Instruments, Inc. CC2531 Dongle
-      if [ "${ti16ae_first}" = "1" ]; then
-        printf '\n## ticc2531 zigbee\n' >> "${kismet_site}"
-        ti16ae_first=0
-      fi
-      printf 'source=ticc2531-%s:type=ticc2531\n' "${BUS}" >> "${kismet_site}"
-      ;;
-    16b3)
-      #Texas Instruments, Inc. CC2540 USB Dongle
-      if [ "${ti16b3_first}" = "1" ]; then
-        printf '\n## ticc2540 ble\n' >> "${kismet_site}"
-        ti16b3_first="0"
-      fi
-      printf 'source=ticc2540-%s:type=ticc2540\n' "${BUS}" >> "${kismet_site}"
-      ;;
-  esac
-done
-unset IFS
-return 0
+  for device in $(lsusb -d '0451:' | tr ":" " "| awk '{print $6":"$7,$2"-"$4}' | sort); do
+    PID="$(printf '%s' "${device}" | awk '{print $1}' | awk -F: '{print $2}')"
+    BUS="$(printf '%s' "${device}" | awk '{print $2}')"
+    case "${PID}" in
+      16ae)
+        #Texas Instruments, Inc. CC2531 Dongle
+        if [ "${ti16ae_first}" = "1" ]; then
+          printf '\n## ticc2531 zigbee\n' >> "${kismet_site}"
+          ti16ae_first=0
+        fi
+        printf 'source=ticc2531-%s:type=ticc2531\n' "${BUS}" >> "${kismet_site}"
+        ;;
+      16b3)
+        #Texas Instruments, Inc. CC2540 USB Dongle
+        if [ "${ti16b3_first}" = "1" ]; then
+          printf '\n## ticc2540 ble\n' >> "${kismet_site}"
+          ti16b3_first="0"
+        fi
+        printf 'source=ticc2540-%s:type=ticc2540\n' "${BUS}" >> "${kismet_site}"
+        ;;
+    esac
+  done
+  unset IFS
+  return 0
 }
 
 detect_rtl() {
+  usb_check || return 0
   #make sure we kill any left over rtl_433
   if pkill rtl_433 > /dev/null 2>&1; then
     sleep 1
@@ -575,7 +601,7 @@ detect_reg() {
 detect_linuxwifi() {
   # XXX: the coconut detection needs to remove things from the wlan detection, and it's a little dumb about it
   coconut_found='0'
-  if [ "$(lsusb -d '148f:5370' | wc -l)" -gt 8 ]; then
+  if [ "${LSUSB}" = "1" ] && [ "$(lsusb -d '148f:5370' | wc -l)" -gt 8 ]; then
     coconut_likely='1'
   else
     coconut_likely='0'
