update ubertooth detection to check for hardware first

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -17,7 +17,7 @@ elif [ -z "${USERID}" ]; then
 	printf 'Unable to determine user id, permission errors may occur.\n'
 fi
 
-VERS="v1.0"
+VERS="v1.1"
 
 blue_hydra="false"
 rtl_skip_zero="false"
@@ -249,15 +249,15 @@ detect_linuxbluetooth() {
 }
 
 detect_ubertooth() {
+  if [ -z "$(lsusb -d '1d50:6002' 2>&1)" ]; then
+    # No ubertooth found, bail out quick
+    return 0
+  fi
   if [ ! -x "$(command -v ubertooth-util)" ]; then
-    if [ -n "$(lsusb -d '1d50:6002' 2>&1)" ]; then
-      printf 'Ubertooth device found using lsusb, but ubertooth tools are not installed\n' >&2
-      printf 'Typically this package is available as "ubertooth".\n' >&2
-      printf '# Ubertooth found, but ubertooth tools are not installed and are required.\n' > "${kismet_site}"
-      return 1
-    else
-      return 0
-    fi
+    printf 'Ubertooth device found using lsusb, but ubertooth tools are not installed\n' >&2
+    printf 'Typically this package is available as "ubertooth".\n' >&2
+    printf '# Ubertooth found, but ubertooth tools are not installed and are required.\n' > "${kismet_site}"
+    return 1
   fi
   uberteeth="$(ubertooth-util -N 2>/dev/null)"
   if [ "${uberteeth}" -gt "0" ]; then
