support nxp and cleanup

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -46,6 +46,11 @@ if [ ! -x "$(command -v pgrep 2>&1)" ]; then
   printf 'this tool is typically available in the "procps" package\n' >&2
   exit 1
 fi
+if [ ! -x "$(command -v lsmod 2>&1)" ]; then
+  printf 'lsmod is required, please install it\n' >&2
+  printf 'this tool is typically available in the "kmod" package\n' >&2
+  exit 1
+fi
 # maybe add support for ncat from nmap?
 if [ ! -x "$(command -v nc 2>&1)" ]; then
   printf 'Some kind of netcat is required as "nc", please install it\n' >&2
@@ -138,42 +143,53 @@ printf 'kismet-autoconfig %s writing to %s\n' "${VERS}" "${kismet_site}" >&2
 
 printf '## WARNING: This file is generated by kismet-autoconfig and cannot be edited!!!\n' > "${kismet_site}"
 
-detect_nxp() {
-  nxp_usb="$(lsusb -d '15a2:0300' | wc -l)"
-  if [ "${nxp_usb}" = "0" ]; then
-    return 0
-  fi
-  nxp_serial="0"
-  all_nxp_accounted="0"
-  [ "${ZSH_NAME:-}" = "zsh" ] && unsetopt nomatch
-  for nxp in /dev/nxp_kw41z* ; do
-    if [ "${nxp}" = "/dev/nxp_kw41z*" ]; then
-      continue
-    fi
-    printf '\n## NXP_KW1Z ble and zigbee sniffer\n' >> "${kismet_site}"
-    printf 'source=nxp_kw41z:device=%s,type=nxp_kw41z,phy=all\n' "${nxp}" >> "${kismet_site}"
-    : $(( nxp_serial += 1 ))
-  done
-  [ "${ZSH_NAME:-}" = "zsh" ] && setopt nomatch
-  if [ "${nxp_usb}" != "${nxp_serial}" ]; then
-    printf 'Detected %s nxp_kw1z but found serial interfaces for %s.\n' "${nxp_usb}" "${nxp_serial}" >&2
-    all_nxp_accounted="1"
-    if [ "${nxp_serial}" = 0 ]; then
-      printf 'Did you forget to install kismet/packaging/udev/99-kismet-nxp-kw41z.rules?\n' >&2
-    fi
-  fi
-  return "${all_nxp_accounted}"
-}
-
 vid_pid_to_dev(){
   if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
     printf 'vid_pid_to_dev requires vid as param one and pid as param two\n'
     exit 1
   fi
-  find $(grep -l "PRODUCT=${1}/${2}" /sys/bus/usb/devices/[0-9]*:*/uevent | sed 's,uevent$,,') \
+  # we want this to be split
+  # shellcheck disable=2046
+  find $(grep -l "PRODUCT=$(printf '%x/%x' "0x${1}" "0x${2}")" /sys/bus/usb/devices/[0-9]*:*/uevent | sed 's,uevent$,,') \
     /dev/null -name dev -o -name dev_id |
     sed 's,[^/]*$,uevent,' |
     xargs sed -n -e s,DEVNAME=,/dev/,p
+}
+
+cdc_acm_check() {
+  if lsmod | grep -q 'cdc_acm' > /dev/null 2>&1; then
+    true
+  else
+    printf 'Kernel module cdc_acm is required but not loaded. Do you need to install it?\n'
+  fi
+}
+
+detect_nxp() {
+  nxp_usb="$(lsusb -d '15a2:0300' | wc -l)"
+  if [ "${nxp_usb}" = "0" ]; then
+    return 0
+  fi
+
+  nxp_serial="0"
+  nxpkw1z_first="1"
+  all_nxp_accounted="0"
+
+  for nxp in $(vid_pid_to_dev 15a2 0300) ; do
+    if [ "${nxpkw1z_first}" = "1" ]; then
+      printf '\n## NXP_KW1Z ble and zigbee sniffer\n' >> "${kismet_site}"
+      nxpkw1z_first="0"
+    fi
+    printf 'source=nxp_kw41z:device=%s,type=nxp_kw41z,phy=all\n' "${nxp}" >> "${kismet_site}"
+    : $(( nxp_serial += 1 ))
+  done
+  if [ "${nxp_usb}" != "${nxp_serial}" ]; then
+    printf 'Detected %s nxp_kw1z but found serial interfaces for %s.\n' "${nxp_usb}" "${nxp_serial}" >&2
+    all_nxp_accounted="1"
+    if [ "${nxp_serial}" = 0 ]; then
+      cdc_acm_check
+    fi
+  fi
+  return "${all_nxp_accounted}"
 }
 
 detect_nordic() {
@@ -231,7 +247,6 @@ detect_nordic() {
   fi
 
   nrf51822_first="1"
-  [ "${ZSH_NAME:-}" = "zsh" ] && unsetopt nomatch
   for nrf51822 in $(vid_pid_to_dev 1915 522a); do
     if [ "${nrf51822_first}" = "1" ]; then
       printf '\n## nrf51822 ble sniffer\n' >> "${kismet_site}"
@@ -240,21 +255,15 @@ detect_nordic() {
     printf 'source=nrf51822:device=%s,type=nrf51822\n' "${nrf51822}" >> "${kismet_site}"
     nrf522a_serial=$(( nrf522a_serial + 1 ))
   done
-  [ "${ZSH_NAME:-}" = "zsh" ] && setopt nomatch
   if [ "${nrf522a_usb}" != "${nrf522a_serial}" ]; then
     printf 'Detected %s nrf51822 but found serial interfaces for %s.\n' "${nrf522a_usb}" "${nrf522a_serial}"
     all_nrf_accounted="1"
     if [ "${nrf522a_serial}" = 0 ]; then
-      if lsmod | grep -q 'cdc_acm' > /dev/null 2>&1; then
-        true
-      else
-        printf 'Do you need to install kernel module cdc_acm?\n'
-      fi
+      cdc_acm_check
     fi
   fi
 
   nrf52840_first="1"
-  [ "${ZSH_NAME:-}" = "zsh" ] && unsetopt nomatch
   for nrf52840 in $(vid_pid_to_dev 1915 154a); do
     if [ "${nrf52840_first}" = 1 ]; then
       printf '\n## nrf52840 802.15.4 sniffer\n' >> "${kismet_site}"
@@ -263,16 +272,11 @@ detect_nordic() {
     printf 'source=nrf52840:device=%s,type=nrf52840\n' "${nrf52840}" >> "${kismet_site}"
     nrf154a_serial=$(( nrf154a_serial + 1 ))
   done
-  [ "${ZSH_NAME:-}" = "zsh" ] && setopt nomatch
   if [ "${nrf154a_usb}" != "${nrf154a_serial}" ]; then
     printf 'Detected %s nrf52840 but found serial interfaces for %s.\n' "${nrf154a_usb}" "${nrf154a_serial}"
     all_nrf_accounted="1"
     if [ "${nrf154a_serial}" = 0 ]; then
-      if lsmod | grep -q 'cdc_acm' > /dev/null 2>&1; then
-        true
-      else
-        printf 'Do you need to install kernel module cdc_acm?\n'
-      fi
+      cdc_acm_check
     fi
   fi
 
@@ -479,7 +483,6 @@ handle_lar() {
       # https://git.kernel.org/pub/scm/linux/kernel/git/wens/wireless-regdb.git/tree/db.txt
       if iw phy "${PHYDEV}" channels | grep -q '5955 MHz .* (disabled)' > /dev/null 2>&1 ; then
         unset vif_name
-        [ "${ZSH_NAME:-}" = "zsh" ] && unsetopt nomatch
         for vif in /sys/class/ieee80211/"${PHYDEV}"/device/net/*; do
           # Checking for managed/client mode
           if [ "$(cat "${vif}/type")" = "1" ]; then
@@ -487,7 +490,6 @@ handle_lar() {
             break
           fi
         done
-        [ "${ZSH_NAME:-}" = "zsh" ] && setopt nomatch
         if [ -z "${vif_name:-}" ]; then
           printf 'Your iwlwifi device %s needs LAR set, but no managed interface is available to do that.\n' "${1}" >&2
           printf 'Please run "airmon-ng stop %s" or create a managed interface manually.\n' "${1}" >&2
