minor text output fix

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -2,7 +2,7 @@
 set -e
 set -u
 
-VERS='v2.3.2'
+VERS='v2.3.3'
 
 blue_hydra="false"
 gentle="false"
@@ -904,7 +904,7 @@ if [ -n "${detect:-}" ]; then
   if detect_"${detect}"; then
     exit 0
   else
-    printf 'FATAL: %s found fatal errors, please review the output carefully.\n' "${0}" 2>&1
+    printf 'FATAL: %s found fatal errors, please review the output carefully.\n' "${0}" >&2
     exit 1
   fi
 else
@@ -912,7 +912,7 @@ else
   if kick_it; then
     exit 0
   else
-    printf 'FATAL: %s found fatal errors, please review the output carefully.\n' "${0}" 2>&1
+    printf 'FATAL: %s found fatal errors, please review the output carefully.\n' "${0}" >&2
     exit 1
   fi
 fi
