loop lar handling so it has a few chances for success

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -2,7 +2,7 @@
 set -e
 set -u
 
-VERS='v2.1.1'
+VERS='v2.2.0'
 
 blue_hydra="false"
 gentle="false"
@@ -611,40 +611,46 @@ handle_lar() {
   if [ -r "/sys/class/net/${1}/phy80211/name" ]; then
     PHYDEV="$(cat "/sys/class/net/${1}/phy80211/name")"
     if [ -n "${PHYDEV:-}" ]; then
-      # If channel 5955 isn't enabled then we know we need to scan
-      # Channel 5955 was chosen because most countries allow 5945 and higher
+      was_down="0"
+      # All countries with wifi 6e seem to allow 5945-6425, so we pick a few channels and check if they are enabled.
       # https://git.kernel.org/pub/scm/linux/kernel/git/wens/wireless-regdb.git/tree/db.txt
-      if iw phy "${PHYDEV}" channels | grep -q '5955 MHz .* (disabled)' > /dev/null 2>&1 ; then
-        unset vif_name
-        for vif in /sys/class/ieee80211/"${PHYDEV}"/device/net/*; do
-          # Checking for managed/client mode
-          if [ "$(cat "${vif}/type")" = "1" ]; then
-            vif_name="${vif##*/}"
-            break
+      for channel in 5955 5975 5995 6015 6035 6055; do
+        if iw phy "${PHYDEV}" channels | grep -q "${channel} MHz .* \(disabled\)" > /dev/null 2>&1 ; then
+          unset vif_name
+          for vif in /sys/class/ieee80211/"${PHYDEV}"/device/net/*; do
+            # Checking for managed/client mode
+            if [ "$(cat "${vif}/type")" = "1" ]; then
+              vif_name="${vif##*/}"
+              break
+            fi
+          done
+          if [ -z "${vif_name:-}" ]; then
+            printf 'FATAL: Your iwlwifi device %s needs LAR set, but no managed interface is available to do that.\n' "${1}" >&2
+            printf 'FATAL: Please run "airmon-ng stop %s" or create a managed interface manually.\n' "${1}" >&2
+            exit 1
           fi
-        done
-        if [ -z "${vif_name:-}" ]; then
-          printf 'FATAL: Your iwlwifi device %s needs LAR set, but no managed interface is available to do that.\n' "${1}" >&2
-          printf 'FATAL: Please run "airmon-ng stop %s" or create a managed interface manually.\n' "${1}" >&2
-          exit 1
-        fi
-        was_down="0"
-        if ! ip link show "${vif_name}" | grep -q 'UP' > /dev/null 2>&1 ; then
-          # when this fails it doesn't exit???
-          ip link set "${vif_name}" up >&2
-          was_down="1"
-        fi
-        if iw "${vif_name}" scan > /dev/null 2>&1; then
-          printf 'INFO: LAR set for %s\n' "${vif_name}" >&2
+          if ! ip link show "${vif_name}" | grep -q 'UP' > /dev/null 2>&1 ; then
+            # when this fails it doesn't exit???
+            ip link set "${vif_name}" up >&2
+            was_down="1"
+          fi
+          if iw "${vif_name}" scan > /dev/null 2>&1; then
+            printf 'INFO: scan triggered for iwlwifi LAR on %s\n' "${vif_name}" >&2
+          else
+            printf 'ERROR: scan failed for iwlwifi LAR failed to set for %s\n' "${vif_name}" >&2
+          fi
+          sleep 1
         else
-          printf 'ERROR: LAR failed to set for %s\n' "${vif_name}" >&2
+          printf 'INFO iwlwifi LAR successfully set on %s\n' "${vif_name}" >&2
         fi
-        sleep 1
-        if [ "${was_down}" = "1" ]; then
-          ip link set "${vif_name}" down >&2
-        fi
+      done
+      if [ "${was_down}" = "1" ]; then
+        ip link set "${vif_name}" down >&2
       fi
     fi
+  fi
+  if iw phy "${PHYDEV}" channels | grep -q "5955 MHz .* \(disabled\)" > /dev/null 2>&1 ; then
+    printf 'ERROR: failed to set iwlwifi LAR by scanning.  You will be unable to use all channels valid in your country.\n' >&2
   fi
   return 0
 }
