yay regdomain

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -136,12 +136,13 @@ if [ -n "${detect:-}" ]; then
     linuxwifi) true ;;
     nordic) true ;;
     nxp) true ;;
+    reg) true ;;
     rtl) true ;;
     ti) true ;;
     ubertooth) true ;;
     *)
       printf 'invalid option --detect %s\n' "${detect}"
-      printf 'Available detections: gps linuxbluetooth linuxwifi nordic nxp rtl ti ubertooth\n'
+      printf 'Available detections: gps linuxbluetooth linuxwifi nordic nxp reg rtl ti ubertooth\n'
       exit 1
       ;;
   esac
@@ -171,11 +172,6 @@ if [ -n "${log_location:-}" ]; then
   fi
 fi
 
-kismet_site=${1:-/dev/stdout}
-printf '## kismet-autoconfig %s writing to %s\n' "${VERS}" "${kismet_site}" >&2
-
-printf '## WARNING: This file is generated by kismet-autoconfig and cannot be edited!!!\n' > "${kismet_site}"
-
 vid_pid_to_dev(){
   if [ -z "${1:-}" ] || [ -z "${2:-}" ]; then
     printf 'vid_pid_to_dev requires vid as param one and pid as param two\n'
@@ -196,6 +192,11 @@ cdc_acm_check() {
     printf 'Kernel module cdc_acm is required but not loaded. Do you need to install it?\n'
   fi
 }
+
+kismet_site=${1:-/dev/stdout}
+printf '## kismet-autoconfig %s writing to %s\n' "${VERS}" "${kismet_site}" >&2
+
+printf '## WARNING: This file is generated by kismet-autoconfig and cannot be edited!!!\n' > "${kismet_site}"
 
 detect_nxp() {
   nxp_usb="$(lsusb -d '15a2:0300' | wc -l)"
@@ -549,6 +550,22 @@ handle_lar() {
   return 0
 }
 
+detect_reg() {
+  if iw reg get | grep -q 'country 00:'; then
+    printf '\nRegulatory Domain appears to be unset, please consider setting it with "iw reg set XX"\n' >&2
+    printf 'https://wireless.wiki.kernel.org/en/users/documentation/iw#updating_your_regulatory_domain\n' >&2
+    printf '\n## Wifi Regulatory Domain appears to be unset, please consider setting it with "iw reg set XX"\n' >> "${kismet_site}"
+    # Should this return 1?
+    return 0
+  else
+    for regdomain in $(iw reg get | awk '/country/ {print substr($2,1,length($2)-1)}' | sort -u); do
+      printf '\nRegulatory Domain set to %s, see "iw reg get" for details\n' "${regdomain}" >&2
+      printf '\n## Wifi Regulatory Domain set to %s\n' "${regdomain}" >> "${kismet_site}"
+    done
+    return 0
+  fi
+}
+
 detect_linuxwifi() {
   # XXX: the coconut detection needs to remove things from the wlan detection, and it's a little dumb about it
   coconut_found='0'
@@ -684,6 +701,7 @@ kick_it() {
   detect_ubertooth || errors_found="1"
   detect_ti || errors_found="1"
   detect_rtl || errors_found="1"
+  detect_reg || errors_found="1"
   detect_linuxwifi || errors_found="1"
   detect_gps || errors_found="1"
   add_log_details || errors_found="1"
