refactor wifi and other updates
- Do not add multiple vifs with the same phy if one is already in
  monitor mode
- Refactor lsusb detection and whining
- redirect line intended for the config file, to the config file

diff --git a/kismet/kismet-autoconfig b/kismet/kismet-autoconfig
--- a/kismet/kismet-autoconfig
+++ b/kismet/kismet-autoconfig
@@ -2,7 +2,7 @@
 set -e
 set -u
 
-VERS='v1.9.12'
+VERS='v2.0.0'
 
 blue_hydra="false"
 gentle="false"
@@ -44,23 +44,19 @@ if [ -d /sys/bus/usb ]; then
   LSUSB_CMD="$(command -v lsusb 2>&1)"
   if [ -x "${LSUSB_CMD}" ]; then
     LSUSB=1
+  elif [ -x "/usr/bin/lsusb" ]; then
+    LSUSB_CMD="/usr/bin/lsusb"
+    LSUSB=1
+  elif [ "${LSUSB_CMD}" = "lsusb" ]; then
+    # busybox built in lsusb, -d 'vendor:' does not do anything, so we avoid it
+    printf 'FATAL: Only the busybox lsusb is available, and it is not currently supported.\n' >&2
+    printf 'FATAL: Please install the full lsusb package from your distro\n' >&2
+    exit 1
   else
-    if [ "${LSUSB_CMD}" = "lsusb" ]; then
-      # XXX busybox lsusb, -d 'vendor:' does not do anything, so we avoid it
-      if [ -x "/usr/bin/lsusb" ]; then
-        LSUSB_CMD="/usr/bin/lsusb"
-        LSUSB=1
-      else
-        printf 'FATAL: Only the busybox lsusb is available, and it is not currently supported.\n' >&2
-        printf 'FATAL: Please install the full lsusb package from your distro\n' >&2
-        exit 1
-      fi
-    else
-      printf 'FATAL: lsusb detected but cannot run.  How did this happen?\n' >&2
-      exit 1
-    fi
+    printf 'FATAL: USB bus detected but unable to find a working "lsusb -d"\n' >&2
+    exit 1
   fi
-# else no usb support needed
+  # else no usb support needed
 fi
 
 # On busybox/ash this returns "lsmod" because it's a built-in
@@ -238,7 +234,7 @@ cdc_acm_check() {
 kismet_site=${1:-/dev/stdout}
 printf '## kismet-autoconfig %s writing to %s\n' "${VERS}" "${kismet_site}" >&2
 
-printf '## WARNING: This file is generated by kismet-autoconfig and cannot be edited!!!\n' > "${kismet_site}"
+printf '## WARNING: This file is generated by kismet-autoconfig %s and cannot be edited!!!\n' > "${kismet_site}" "${VERS}"
 
 detect_nxp() {
   usb_check || return 0
@@ -671,15 +667,30 @@ detect_linuxwifi() {
   fi
   printf '\n## Wifi\n' >> "${kismet_site}"
   for wlan in ${wlan_devices}; do
-    #check off phys and only do each one once, picking interfaces already in monitor mode if available
-    #PHYDEV="$(cat "/sys/class/net/${wlan}/phy80211/name")"
     if [ -n "${wifi_backhaul:-}" ]; then
       printf 'INFO: Ignoring device %s because it is being used as wifi backhaul\n' "${wlan}" >&2
       printf '# Ignoring device %s because it is being used as wifi backhaul\n' "${wlan}" >> "${kismet_site}"
       continue
     fi
     # this interates over all the vif's passed, even if there are multiple vifs per phy
-    # kismet handles it fine, but that's yucky
+    # pick interfaces already in monitor mode if available
+    # kismet device duplication fine, but that's yucky so we avoid when possible
+    MONITOR_FOUND="false"
+    PHYDEV="$(cat "/sys/class/net/${wlan}/phy80211/name")"
+    if [ -d "/sys/class/ieee80211/${PHYDEV}/device/net" ]; then
+      for i in "/sys/class/ieee80211/${PHYDEV}/device/net"/* ; do
+        if [ "$(basename "${i}")" != "${wlan}" ] && [ "$(cat "${i}/type")" = "803" ]; then
+          printf 'INFO: Ignoring %s because it shares a phy (%s) with monitor mode vif %s\n' "${wlan}" "${PHYDEV}" "$(basename "${i}")" >&2
+          printf '# Ignoring %s because it shares a phy (%s) with monitor mode vif %s\n' "${wlan}" "${PHYDEV}" "$(basename "${i}")" >> "${kismet_site}"
+          printf '# source=%s:default_ht20=true,type=linuxwifi\n' "${wlan}" >> "${kismet_site}"
+          MONITOR_FOUND="true"
+          break
+        fi
+      done
+    fi
+    if [ "${MONITOR_FOUND}" = "true" ]; then
+      continue
+    fi
     if [ -r "/sys/class/net/${wlan}/device/uevent" ]; then
       DRIVER="$(awk -F'=' '$1 == "DRIVER" {print $2}' "/sys/class/net/${wlan}/device/uevent")"
       if [ -n "${DRIVER:-}" ]; then
@@ -704,7 +715,7 @@ detect_linuxwifi() {
 }
 
 detect_gps() {
-  printf '\n## gps\n'
+  printf '\n## gps\n' >> "${kismet_site}"
   if ss -nlt 2>&1 | grep -q '127.0.0.1:2947'; then
     gps_device="false"
     for gps in $(printf '?DEVICES;' | timeout 1 nc ${nc_flags:-} localhost 2947 2>&1 | jq -eM 'select (.class=="DEVICES") | ."devices"[]."path"'); do
